package org.bread_experts_group.api.graphics.feature.window.feature.event_loop.mouse.x2d.left.down

import org.bread_experts_group.api.graphics.feature.window.feature.event_loop.GraphicsWindowEventLoopEventParameter

interface GraphicsWindowEventLoopMouseLeft2DDownEventParameter : GraphicsWindowEventLoopEventParameter