@file:Suppress("ObjectPropertyName", "DANGEROUS_CHARACTERS", "SpellCheckingInspection")

package org.bread_experts_group.ffi.windows

import org.bread_experts_group.ffi.nativeLinker
import java.lang.foreign.AddressLayout
import java.lang.foreign.ValueLayout

private val mappings = nativeLinker.canonicalLayouts()

const val UNICODE = true

// TODO: 32-bit/64-bit separation
val int64_t = mappings["int64_t"]!! as ValueLayout
val wchar_t = mappings["wchar_t"]!! as ValueLayout.OfChar
val char = mappings["char"]!! as ValueLayout
val short = mappings["short"]!! as ValueLayout
val int = mappings["int"]!! as ValueLayout.OfInt
val long = mappings["long"]!! as ValueLayout.OfInt
val float = mappings["float"]!! as ValueLayout
val double = mappings["double"]!! as ValueLayout
val `void*` = mappings["void*"]!! as AddressLayout
val size_t = mappings["size_t"]!! as ValueLayout

val __int64 = int64_t
val _WIN64 = size_t.byteSize() == 8L
val _MX_IX86 = System.getProperty("os.arch") == "x86"

val BYTE = char // unsigned
val WORD = short // unsigned
val DWORD = long // unsigned
val LONG = long

val PVOID = `void*`

val ATOM = WORD
val BOOL = int
val BOOLEAN = BYTE
val CCHAR = char
val CHAR = char
val COLORREF = DWORD
val DWORDLONG = __int64 // unsigned
val ULONG_PTR = size_t
val DWORD_PTR = ULONG_PTR
val DWORD32 = int // unsigned
val DWORD64 = __int64 // unsigned
val FLOAT = float
val HANDLE = PVOID
val HACCEL = HANDLE
val HALF_PTR = if (_WIN64) int else short
val HBITMAP = HANDLE
val HBRUSH = HANDLE
val HCOLORSPACE = HANDLE
val HCONV = HANDLE
val HCONVLIST = HANDLE
val HICON = HANDLE
val HCURSOR = HICON
val HDC = HANDLE
val HDDEDATA = HANDLE
val HDESK = HANDLE
val HDROP = HANDLE
val HDWP = HANDLE
val HENHMETAFILE = HANDLE
val HFILE = int
val HFONT = HANDLE
val HGDIOBJ = HANDLE
val HGLOBAL = HANDLE
val HHOOK = HANDLE
val HINSTANCE = HANDLE
val HKEY = HANDLE
val HKL = HANDLE
val HLOCAL = HANDLE
val HMENU = HANDLE
val HMETAFILE = HANDLE
val HMODULE = HANDLE
val HMONITOR = HANDLE
val HPALETTE = HANDLE
val HPEN = HANDLE
val HRESULT = LONG
val HRGN = HANDLE
val HRSRC = HANDLE
val HSZ = HANDLE
val HWINSTA = HANDLE
val HWND = HANDLE
val INT = int
val INT_PTR = if (_WIN64) __int64 else int
val INT8 = char
val INT16 = short
val INT32 = int
val INT64 = __int64
val LANGID = WORD
val LCID = DWORD
val LCTYPE = DWORD
val LGRPID = DWORD
val LONGLONG = if (!_MX_IX86) __int64 else double
val LONG_PTR = size_t
val LONG32 = int
val LONG64 = __int64
val LPARAM = LONG_PTR
val LPBOOL = `void*` // BOOL far
val LPBYTE = `void*` // BYTE far
val LPCOLORREF = `void*` // DWORD
val LPCSTR = `void*` // CONST CHAR
val LPCWSTR = `void*` // WCHAR
val LPCTSTR = if (UNICODE) LPCWSTR else LPCSTR
val LPCVOID = `void*`
val LPDWORD = `void*` // DWORD
val LPHANDLE = `void*` // HANDLE
val LPINT = `void*` // int
val LPLONG = `void*` // long
val LPSTR = `void*` // char
val LPWSTR = `void*` // WCHAR
val LPTSTR = if (UNICODE) LPWSTR else LPSTR
val LPVOID = `void*`
val LPWORD = `void*` // WORD
val LRESULT = LONG_PTR
val PBOOL = `void*` // BOOL
val PBOOLEAN = `void*` // BOOLEAN
val PBYTE = `void*` // BYTE
val PCHAR = `void*` // CHAR
val PCSTR = `void*` // CHAR
val PCTSTR = if (UNICODE) LPCWSTR else LPCSTR
val PCWSTR = `void*` // WCHAR
val PDWORD = `void*` // DWORD
val PDWORDLONG = `void*` // DWORDLONG
val PDWORD_PTR = `void*` // DWORD_PTR
val PDWORD32 = `void*` // DWORD32
val PDWORD64 = `void*` // DWORD64
val PFLOAT = `void*` // FLOAT
val PHALF_PTR = `void*` // HALF_PTR
val PHANDLE = `void*` // HANDLE
val PHKEY = `void*` // HKEY
val PINT = `void*` // int
val PINT_PTR = `void*` // INT_PTR
val PINT8 = `void*` // INT8
val PINT16 = `void*` // INT16
val PINT32 = `void*` // INT32
val PINT64 = `void*` // INT64
val PLCID = `void*` // PDWORD
val PLONG = `void*` // LONG
val PLONGLONG = `void*` // LONGLONG
val PLONG_PTR = `void*` // LONG_PTR
val PLONG32 = `void*` // LONG32
val PLONG64 = `void*` // LONG64

//val POINTER_32 = 0 // ???
//val POINTER_64 = 1 // ???
//val POINTER_SIGNED = 0 // ???
//val POINTER_UNSIGNED = 0 // ???

val PSHORT = `void*` // SHORT
val PSIZE_T = `void*` // SIZE_T
val PSSIZE_T = `void*` // SSIZE_T
val PSTR = `void*` // CHAR
val PTBYTE = `void*` // TBYTE
val PTCHAR = `void*` // TCHAR
val PTSTR = if (UNICODE) LPWSTR else LPSTR
val PUCHAR = `void*` // UCHAR
val PUHALF_PTR = `void*` // UHALF_PTR
val PUINT = `void*` // UINT
val PUINT_PTR = `void*` // UINT_PTR
val PUINT8 = `void*` // UINT8
val PUINT16 = `void*` // UINT16
val PUINT32 = `void*` // UINT32
val PUINT64 = `void*` // UINT64
val PULONG = `void*` // ULONG
val PULONGLONG = `void*` // ULONGLONG
val PULONG_PTR = `void*` // ULONG_PTR
val PULONG32 = `void*` // ULONG32
val PULONG64 = `void*` // ULONG64
val PUSHORT = `void*` // USHORT
val PWCHAR = `void*` // WCHAR
val PWORD = `void*` // WORD
val PWSTR = `void*` // WCHAR
val QWORD = __int64 // unsigned
val SC_HANDLE = HANDLE
val SC_LOCK = LPVOID
val SERVICE_STATUS_HANDLE = HANDLE
val SHORT = short
val SIZE_T = ULONG_PTR
val SSIZE_T = LONG_PTR
val WCHAR = wchar_t
val TBYTE = if (UNICODE) WCHAR else char // unsigned
val TCHAR = if (UNICODE) WCHAR else char
val UCHAR = char // unsigned
val UHALF_PTR = if (_WIN64) int else short // unsigned
val UINT = int // unsigned
val UINT_PTR = if (_WIN64) __int64 else int // unsigned
val UINT8 = char // unsigned
val UINT16 = short // unsigned
val UINT32 = int // unsigned
val UINT64 = __int64 // unsigned
val ULONG = long // unsigned
val ULONGLONG = if (!_MX_IX86) __int64 /* unsigned */ else double
val ULONG32 = int // unsigned
val ULONG64 = __int64 // unsigned
val USHORT = short // unsigned
val USN = LONGLONG
val WPARAM = UINT_PTR