package org.bread_experts_group.dns

enum class DNSResponseCode(val code: Int) {
	OK(0),
	FORMAT_ERROR(1),
	SERVER_FAILURE(2),
	NONEXISTENT_DOMAIN(3),
	NOT_IMPLEMENTED(4),
	SERVER_REFUSED(5),
	PARADOXICAL_DOMAIN(6),
	PARADOXICAL_RECORD_SET(7),
	MISSING_RECORD_SET(8),
	SERVER_NOT_AUTHORITATIVE(9),
	NOT_IN_ZONE(10),
	DSO_TYPE_NOT_IMPLEMENTED(11),
	BAD_OPT_VERSION(16),
	BAD_TSIG_SIGNATURE(16),
	BAD_KEY(17),
	BAD_SIGNATURE_TIME(18),
	BAD_TSIG_MODE(19),
	DUPLICATE_KEY_NAME(20),
	ALGORITHM_NOT_SUPPORTED(21),
	BAD_TRUNCATION(22),
	BAD_SERVER_COOKIE(23),
	OTHER(-1);

	companion object {
		val mapping: Map<Int, DNSResponseCode> = entries.associateBy(DNSResponseCode::code)
	}
}