package org.bread_experts_group.api.graphics.feature.window.feature.event_loop.redraw

import org.bread_experts_group.api.graphics.feature.window.feature.event_loop.GraphicsWindowEventLoopEventParameter

interface GraphicsWindowEventLoopRedrawEventParameter : GraphicsWindowEventLoopEventParameter