package org.bread_experts_group.api.graphics.feature.window.feature.event_loop.mouse.x2d.move

import org.bread_experts_group.api.graphics.feature.window.feature.event_loop.GraphicsWindowEventLoopEventParameter

interface GraphicsWindowEventLoopMouseMove2DEventParameter : GraphicsWindowEventLoopEventParameter