package org.bread_experts_group.project_incubator.maven2.networking

import org.bread_experts_group.project_incubator.maven2.CapabilityProvider

interface NetworkingProvider : CapabilityProvider<NetworkingDevice>