package org.bread_experts_group.ffi.windows.directx

import java.lang.foreign.MemorySegment

class IDXGIFactory3(
	ptr: MemorySegment,
	iUnknownQueryInterfaceVTblIndex: Int,
	iUnknownAddRefVTblIndex: Int,
	iUnknownReleaseVTblIndex: Int,
	iDXGIObjectSetPrivateDataVTblIndex: Int,
	iDXGIObjectSetPrivateDataInterfaceVTblIndex: Int,
	iDXGIObjectGetPrivateDataVTblIndex: Int,
	iDXGIObjectGetParentVTblIndex: Int,
	iDXGIFactoryEnumAdaptersVTblIndex: Int,
	iDXGIFactoryMakeWindowAssociationVTblIndex: Int,
	iDXGIFactoryGetWindowAssociationVTblIndex: Int,
	iDXGIFactoryCreateSwapChainVTblIndex: Int,
	iDXGIFactoryCreateSoftwareAdapterVTblIndex: Int,
	iDXGIFactory1EnumAdapters1VTblIndex: Int,
	iDXGIFactory1IsCurrentVTblIndex: Int,
	iDXGIFactory2IsWindowedStereoEnabledVTblIndex: Int,
	iDXGIFactory2CreateSwapChainForHwndVTblIndex: Int,
	iDXGIFactory2CreateSwapChainForCoreWindowVTblIndex: Int,
	iDXGIFactory2GetSharedResourceAdapterLuidVTblIndex: Int,
	iDXGIFactory2RegisterStereoStatusWindowVTblIndex: Int,
	iDXGIFactory2RegisterStereoStatusEventVTblIndex: Int,
	iDXGIFactory2UnregisterStereoStatusVTblIndex: Int,
	iDXGIFactory2RegisterOcclusionStatusWindowVTblIndex: Int,
	iDXGIFactory2RegisterOcclusionStatusEventVTblIndex: Int,
	iDXGIFactory2UnregisterOcclusionStatusVTblIndex: Int,
	iDXGIFactory2CreateSwapChainForCompositionVTblIndex: Int,
	getCreationFlagsVTblIndex: Int,
	vTblReinterpretationLength: Int
) : IDXGIFactory2(
	ptr,
	iUnknownQueryInterfaceVTblIndex,
	iUnknownAddRefVTblIndex,
	iUnknownReleaseVTblIndex,
	iDXGIObjectSetPrivateDataVTblIndex,
	iDXGIObjectSetPrivateDataInterfaceVTblIndex,
	iDXGIObjectGetPrivateDataVTblIndex,
	iDXGIObjectGetParentVTblIndex,
	iDXGIFactoryEnumAdaptersVTblIndex,
	iDXGIFactoryMakeWindowAssociationVTblIndex,
	iDXGIFactoryGetWindowAssociationVTblIndex,
	iDXGIFactoryCreateSwapChainVTblIndex,
	iDXGIFactoryCreateSoftwareAdapterVTblIndex,
	iDXGIFactory1EnumAdapters1VTblIndex,
	iDXGIFactory1IsCurrentVTblIndex,
	iDXGIFactory2IsWindowedStereoEnabledVTblIndex,
	iDXGIFactory2CreateSwapChainForHwndVTblIndex,
	iDXGIFactory2CreateSwapChainForCoreWindowVTblIndex,
	iDXGIFactory2GetSharedResourceAdapterLuidVTblIndex,
	iDXGIFactory2RegisterStereoStatusWindowVTblIndex,
	iDXGIFactory2RegisterStereoStatusEventVTblIndex,
	iDXGIFactory2UnregisterStereoStatusVTblIndex,
	iDXGIFactory2RegisterOcclusionStatusWindowVTblIndex,
	iDXGIFactory2RegisterOcclusionStatusEventVTblIndex,
	iDXGIFactory2UnregisterOcclusionStatusVTblIndex,
	iDXGIFactory2CreateSwapChainForCompositionVTblIndex,
	vTblReinterpretationLength
) {
	constructor(ptr: MemorySegment) : this(
		ptr,
		0,
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10,
		11,
		12,
		13,
		14,
		15,
		16,
		17,
		18,
		19,
		20,
		21,
		22,
		23,
		24,
		25,
		26
	)

	var getCreationFlags = {
		TODO("Not yet implemented")
	}
}