@file:Suppress("FunctionName")

package org.bread_experts_group.protocol.vt100d

const val VT100D_ESC = '\u001B'

const val CONTROL_SEQUENCE_INTRODUCER = "$VT100D_ESC["
fun CURSOR_UP(offset: UShort) = "${CONTROL_SEQUENCE_INTRODUCER}${offset}A"
fun CURSOR_DOWN(offset: UShort) = "${CONTROL_SEQUENCE_INTRODUCER}${offset}B"
fun CURSOR_RIGHT(offset: UShort) = "${CONTROL_SEQUENCE_INTRODUCER}${offset}C"
fun CURSOR_LEFT(offset: UShort) = "${CONTROL_SEQUENCE_INTRODUCER}${offset}D"
fun CURSOR_X_POS(x: UShort) = "${CONTROL_SEQUENCE_INTRODUCER}${x}G"
fun CURSOR_Y_POS(y: UShort) = "${CONTROL_SEQUENCE_INTRODUCER}${y}d"
fun CURSOR_XY_POS(x: UShort, y: UShort) = "${CONTROL_SEQUENCE_INTRODUCER}${y};${x}H"
fun SET_ATTRIBUTE(attribute: VT100DGraphicsAttributes) = "${CONTROL_SEQUENCE_INTRODUCER}${attribute.id}m"
fun SET_EXT_FG(r: UByte, g: UByte, b: UByte) = "${CONTROL_SEQUENCE_INTRODUCER}38;2;$r;$g;${b}m"
fun SET_EXT_BG(r: UByte, g: UByte, b: UByte) = "${CONTROL_SEQUENCE_INTRODUCER}48;2;$r;$g;${b}m"
fun ERASE_CHARACTERS(n: UShort) = "${CONTROL_SEQUENCE_INTRODUCER}${n}X"
const val OPEN_ALT_BUFFER = "${CONTROL_SEQUENCE_INTRODUCER}?1049h"
const val USE_MAIN_BUFFER = "${CONTROL_SEQUENCE_INTRODUCER}?1049l"
const val CURSOR_SHOW = "${CONTROL_SEQUENCE_INTRODUCER}?25h"
const val CURSOR_HIDE = "${CONTROL_SEQUENCE_INTRODUCER}?25l"
const val CURSOR_BLINKING = "${CONTROL_SEQUENCE_INTRODUCER}?12h"
const val CURSOR_NO_BLINKING = "${CONTROL_SEQUENCE_INTRODUCER}?12l"
fun ERASE_SCREEN(types: VT100DEraseTypes) = "${CONTROL_SEQUENCE_INTRODUCER}${types.n}J"
fun ERASE_LINE(types: VT100DEraseTypes) = "${CONTROL_SEQUENCE_INTRODUCER}${types.n}K"

const val OPERATING_SYSTEM_COMMAND = "$VT100D_ESC]"
const val STRING_TERMINATOR = "$VT100D_ESC\\"
fun SET_WINDOW_TITLE(title: String) = "${OPERATING_SYSTEM_COMMAND}2;$title$STRING_TERMINATOR"
fun SET_PALETTE(
	index: Int,
	r: UByte, g: UByte, b: UByte
) = "${OPERATING_SYSTEM_COMMAND}4;$index;$r/$g/$b$STRING_TERMINATOR"