package org.bread_experts_group.api.system.device.transparent_encrypt

enum class WindowsTransparentEncryptionDisableFeatures : DisableTransparentEncryptionSystemDeviceFeatureIdentifier {
	DIRECTORY
}