package org.bread_experts_group.api.system.device.copy

enum class WindowsCopySystemDeviceFeatures : CopySystemDeviceFeatureIdentifier {
	FAIL_IF_DESTINATION_EXISTS,
	RESTARTABLE,
	RESUME_FROM_RESTART,
	OPEN_SOURCE_FOR_WRITE,
	ALLOW_UNENCRYPTED_DESTINATION,
	COPY_SYMBOLIC_LINK,
	DISABLE_SYSTEM_CACHE,
	DISABLE_WINDOWS_COPY_OFFLOAD,
	NO_BLOCK_DESTINATION_ENCRYPT,
	IGNORE_SOURCE_ENCRYPTION,
	NO_DESTINATION_WRITE_DAC,
	ALWAYS_COPY_REPARSE_POINT,
	DIRECTORY,
	IGNORE_ALT_STREAMS,
	DISABLE_PRE_ALLOCATION,
	LOW_SPACE_FREE_MODE,
	COMPRESS_OVER_LINK,
	SPARSENESS,
	DISABLE_COPY_JUNCTIONS
}