package org.bread_experts_group.api.system.device.io

enum class WindowsIOOpenFeatures : OpenIODeviceFeatureIdentifier {
	ARCHIVE,
	ENCRYPT,
	HIDDEN,
	REFS_INTEGRITY,
	READ_ONLY,
	SYSTEM,
	OPTIMIZE_TEMPORARY,
	DELETE_ON_CLOSE,
	DISABLE_SYSTEM_BUFFERING,
	DISABLE_REMOTE_RECALL,
	DISABLE_REDIRECTION,
	OPEN_REPARSE_POINT,
	OPTIMIZE_RANDOM_ACCESS,
	OPTIMIZE_SEQUENTIAL_ACCESS,
	WRITE_THROUGH
}