package org.bread_experts_group.api.system.io.open

import org.bread_experts_group.api.system.device.metadata.MetadataSystemDeviceDataIdentifier

interface OpenIODeviceDataIdentifier : MetadataSystemDeviceDataIdentifier