package org.bread_experts_group.api.graphics.feature.window.feature.event_loop.keyboard.up

import org.bread_experts_group.api.graphics.feature.window.feature.event_loop.GraphicsWindowEventLoopEventParameter

interface GraphicsWindowEventLoopKeyboardKeyUpEventParameter : GraphicsWindowEventLoopEventParameter